jenkinsci/kubernetes-operator

- Gopkg.lock
- pkg/controller/jenkins/plugins/base_plugins.go
- scripts/getLatestVersions.sh
Ran into problems setting newer versions of plugins in the jenkins *instance* yaml than the versions in `base_plugins.go`. For maintenance and consistency, I moved all the single-use plugin versions to the same `const` declaration as the other versions and sorted them. Also added a bash script (plenty of room for improvement) to help checking for newer versions.
I'd really like the jenkins-operator to allow specifying newer versions of base plugins in the *instance* yaml. Especially if you have a team that uses one operator in a given namespace, but multiple instances of Jenkins in the same namespace.
Script output before updating the plugins:
```
PLUGIN ID                               LOCAL VERSION  LATEST                          NEW PLUGIN:VERSION
ace-editor …
```
> Update and Sort Base Plugins

- docs/developer-guide.md
- docs/install_dev_tools.md
Add install_dev_tools.md to add build dependencies
Add a link in develop_guide.md to install_dev_tools.md
Develop with remote k8s server
> Add documentation to allow development with remote k8s server

- website/content/en/blog/news/second-post.md
- website/content/en/blog/releases/in-depth-monoliths-detailed-spec.md
> Fix #134: couple of misspellings (Hacktoberfest)

- website/content/en/docs/How it works/_index.md
- website/content/en/docs/How it works/architecture-and-design.md
Fix misspellings in docs #134 #hacktoberfest
> Fix misspellings in docs #134

- go.mod
- go.sum
- pkg/controller/jenkins/configuration/base/reconcile.go
- pkg/controller/jenkins/configuration/base/reconcile_test.go
- pkg/controller/jenkins/configuration/base/resources.go
- pkg/controller/jenkins/configuration/base/validate.go
- pkg/controller/jenkins/configuration/base/validate_test.go
- pkg/controller/jenkins/configuration/configuration.go
- pkg/controller/jenkins/configuration/user/reconcile.go
- pkg/controller/jenkins/configuration/user/seedjobs/seedjobs.go
- pkg/controller/jenkins/configuration/user/seedjobs/seedjobs_test.go
- pkg/controller/jenkins/configuration/user/seedjobs/validate.go
- pkg/controller/jenkins/configuration/user/seedjobs/validate_test.go
- pkg/controller/jenkins/configuration/user/validate.go
- pkg/controller/jenkins/jenkins_controller.go
* Provide extended Go Kubernetes client with features like terminating master pod. 
* Improve notification feature - send a notification when Jenkins master pod is terminating.
> WIP: Extend kubernetes interface API 

- pkg/controller/jenkins/configuration/base/resources/init_configuration_configmap.go
- pkg/controller/jenkins/configuration/base/resources/pod.go
- pkg/controller/jenkins/configuration/base/resources/scripts_configmap.go
- pkg/controller/jenkins/configuration/base/validate_test.go
- Able to set JENKINS_HOME env variable
> Make Jenkins_Home overwritable

- pkg/controller/jenkins/configuration/base/reconcile.go
* Fixed bug - username/password change message when ConfigMap replaced, but old username/password combination works
* Fixed bug - multiple messages when the `Jenkins` terminating
> #163 Fix misleading messages

- Makefile
- pkg/controller/jenkins/configuration/user/seedjobs/seedjobs.go
- pkg/controller/jenkins/configuration/user/seedjobs/seedjobs_test.go
- test/e2e/configuration_test.go
* Due to bug reported in #173 issue, now `user` configuration phase will wait for the seed job agent and will continue work if the agent will be available and ready
> #173 Add waiting mechanism for seed job agent

- pkg/controller/jenkins/client/jenkins.go
This pull request fixes issue #303
> Add cookie jar to present session cookie for Jenkins API Calls.

- deploy/crds/jenkins.io_jenkins_crd.yaml
- pkg/apis/jenkins/v1alpha2/jenkins_types.go
- pkg/apis/jenkins/v1alpha2/zz_generated.openapi.go
omitempty fields should be `+optional` . Ran `operator-sdk generate openapi` thereafter. 
Master seems to be `required`.
> Mark Master as required and omitempty fields as +optional

- pkg/apis/jenkins/v1alpha2/jenkins_types.go
- pkg/controller/jenkins/configuration/base/resources/scripts_configmap.go
- pkg/controller/jenkins/configuration/base/validate.go
- pkg/controller/jenkins/plugins/plugin.go
- pkg/controller/jenkins/plugins/plugin_test.go
- test/e2e/jenkins.go
> Allow to specify custom plugins location in jenkins CR

- .github/issue_template.md
- .github/pull_request_template.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
- SUPPORT.md
- Update README.md
- Added issue and PR Templates
- Added CONTRIBUTING.md, SECURITY.md, CODE_OF_CONDUCT.md, SUPPORT.md
These changes are made based on the upstream approved documentation https://github.com/jenkinsci/.github with a few additions. 
review them:
```
Describe any user …
```
> Update README.md and add supporting docs with Issue and PR Templates

- pkg/controller/jenkins/configuration/base/configmap.go
- pkg/controller/jenkins/configuration/base/container.go
- pkg/controller/jenkins/configuration/base/label.go
- pkg/controller/jenkins/configuration/base/plugin.go
- pkg/controller/jenkins/configuration/base/pod.go
- pkg/controller/jenkins/configuration/base/rbac.go
- pkg/controller/jenkins/configuration/base/reconcile.go
- pkg/controller/jenkins/configuration/base/service.go
- pkg/controller/jenkins/configuration/base/serviceaccount.go
- pkg/controller/jenkins/configuration/base/validate.go
To prepare refactoring, this is an initial split of the reconcile.go
review them:
```
- API changes
- Bug fixes
```
> Split reconcile.go into several files

- .travis.yml
- Makefile
- config.base.env
- test/e2e/helm_test.go
- add Helm Chart lint test
- add Helm Chart e2e test
review them:
> Add e2e tests for the Helm Chart

- pkg/controller/jenkins/configuration/user/reconcile.go
This fixes #351. Yaml decalared user configuration is reconciled before groovy one
review them:
> Reconcile yaml user configuration before groovy one

- chart/jenkins-operator/templates/role.yaml
This should fix #362  and #361 
review them:
```
- API changes
- Bug fixes
```
> add serviceaccounts update verb to opertor role in helm

- README.md
Updated typo in Readme wrt Google Meet spelling.
review them:
```
- API changes
- Bug fixes
```
> Typo in README for Google Meet

- .travis.yml
- Makefile
- build/Dockerfile
- cicd/pipelines/k8s.jenkins
- config.base.env
Upgrades golang to 1.14
review them:
> Move to golang 1.14

- cmd/manager/main.go
- deploy/role.yaml
- pkg/apis/apis.go
This reverts commit 445cf2eb8c498b015eab2c867a52b00420f8037b.
The commit that is being reverted back as the operator is not able to create Routes or Deployments because these schemes arent registered with the Operator.
```
2020-06-13T19:57:38.569+0530    INFO    controller-jenkins      jenkins/handler.go:88   *v1alpha2.Jenkins/jenkins has been updated   {"cr": "jenkins"}                             
2020-06-13T19:57:42.907+0530    WARN    controller-jenkins      jenkins/jenkins_controller.go:154   Reconcile loop failed: no kind is registered for the type v1.Route in scheme "pkg/runtime/scheme.go:101"      {"cr": "jenkins"}
2020-06-13T19:57:46.188+0530    WARN    controller-jenkins      jenkins/jenkins_controller.go:154   Reconcile loop failed: no kind is registered for the type v1.Route …
```
> Fix GVK Parsng and restore Types in Schema

- deploy/role.yaml
- pkg/configuration/base/route.go
review them:
```
- API changes
- Bug fixes
```
> Fix rout name

- deploy/role.yaml
review them:
```
- API changes
- Bug fixes
```
> add routes resources authorization to jenkins-operator service account

- website/content/en/docs/Getting Started/latest/configuration.md
ssh private key authentication seems to require labels, and annotations are very helpful
review them:
- [ n/a ] Includes tests (if functionality changed/added)
- [ y ] Includes docs (if user facing)
- [ kinda ] Commit messages follow [commit message best practices](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md#commit-messages) …
> add labels and annotations to example of ssh private key configuration

- .github/workflows/auto-gen-docs.yaml
Added GitHub Actions' workflow for automatic docs generation.
> Add GitHub Action for docs generation

- chart/jenkins-operator/crds/jenkinsimage-crd.yaml
- website/content/en/docs/Installation/_index.md
> #503 Added JenkinsImage crd to Helm Chart

- controllers/jenkins_controller.go
- pkg/configuration/base/resources/probe.go
- test/e2e/configuration_test.go
- test/e2e/jenkins_configuration_test.go
- test/e2e/jenkins_pod_restart_test.go
- test/e2e/jenkins_restore_backup_test.go
- test/e2e/jenkins_test.go
- test/e2e/restart_test.go
- test/e2e/restorebackup_test.go
- test/e2e/seedjobs_test.go
- test/e2e/suite_test.go
- test/e2e/wait_test.go
Added tests for plugins in Configuration test, tests for restarts and test of backup and restore.
> Added TestPlugins, TestRestart and TestRestoreBackup

- README.md
> Fix README.md latest schema link

- chart/jenkins-operator/templates/role.yaml
- config/all_in_one_v1alpha2.yaml
- config/rbac/role.yaml
- main.go
- pkg/configuration/base/resources/rbac.go
Added missing permissions for listing events by Jenkins
> #507 Allow listing events

- controllers/handler.go
Added extra logs for create/delete events from Jenkins pod.
> Extra Logs for Create/Delete Events for Jenkins Pod

- .github/workflows/auto-tests.yaml
- pkg/client/jenkins.go
Add security-validator branch to tests triggers (GSoC)
> Add validation branch to tests

- website/content/en/docs/Getting Started/_index.md
- website/content/en/docs/Installation/_index.md
Reorganized instructions on Installation page, fixed link to Installation page on Getting Started index.
> Separate instructions on YAML vs Helm installation in docs

- docs/docs/getting-started/index.html
- docs/docs/installation/index.html
Regenerated docs after Installation page fixes
> Regerate docs

- Makefile
Added a makefile goal to run docs locally
> Makefile goal to run docs locally

- Makefile
- PROJECT
- api/v1alpha2/jenkins_types.go
- api/v1alpha2/jenkins_webhook.go
- chart/jenkins-operator/templates/jenkins.yaml
- chart/jenkins-operator/values.yaml
- config/crd/bases/jenkins.io_jenkins.yaml
- config/webhook/manifests.yaml
- config/webhook/service.yaml
- main.go
- webhook/all_in_one_v1alpha2.yaml
- webhook/cert-manager.yaml
- webhook/operator.yaml
- webhook/rbac.yaml
- webhook/webhook.yaml
- Scaffolded a new validation webhook using operator-sdk
- Added manifests for webhook.
- Added manifests for self signed issuer and certificates
- Added a new spec named ValidateSecurityWarnings to the Jenkins custom resource definition to enable/disable security check.
- Updated Makefile to deploy the operator locally.
review them: …
> Added validation webhook,cert-manager,and updated Makefile.

- .github/stale.yml
Added configuration for https://github.com/probot/stale to help deal with stale issues.
> Configure bot for managing stale issues

- website/content/en/docs/Getting Started/latest/configure-backup-and-restore.md
- website/content/en/docs/Getting Started/v0.5.x/configure-backup-and-restore.md
Related to https://github.com/jenkinsci/kubernetes-operator/issues/530
Made the description of command executing get-latest script less confusing
> Docs: clarification of description of get latest command in backup

- README.md
- chart/jenkins-operator/values.yaml
- website/content/en/docs/Developer Guide/_index.md
- website/content/en/docs/Getting Started/latest/configuration.md
- website/content/en/docs/Getting Started/latest/customization.md
- website/content/en/docs/Installation/_index.md
* Link to project's DockerHub in README
* Append section on nightly builds to Installation docs
* Append section on Jenkins home Volume to Installation docs and add a note on that in default values.yaml
* Revisit sample seedJob configuration with SSH auth in  Configuration docs
* Fix formatting and update plugin versions in Customization docs
> Docs: minor fixes

- .github/ISSUE_TEMPLATE/documentation.md
Adds an issue template for problems with documentation
> Template for issues related to documentation

- chart/index.yaml
Just a quick fix for bad identation introduced in https://github.com/jenkinsci/kubernetes-operator/pull/618
review them:
> Fix bad identation in chart/index.yaml

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- ROADMAP.md
* Removed Contributor Covenant version from Code of Conduct doc
* Added a note on PRs with changes to Helm Chart to CONTRIBUTING doc
* Mentioned Discourse as current main channel of communication in README
* Updated ROADMAP
> Update project and repo documents

- .github/workflows/release-helm-chart.yaml
- Makefile
* Adds Makefile target to package new Helm chart release and deploy it without having user tinker with index.yaml. 
* Adds workflow that updates Chart.yaml with Chart and app version specified by the user (on manual dispatch of workflow) and runs said Makefile target and submits a PR with release
review them:
> Workflow: Release Helm chart

- website/content/en/docs/Getting Started/latest/customizing-jenkins.md
- website/content/en/docs/Getting Started/latest/installing-the-operator.md
- website/content/en/docs/Getting Started/latest/schema.md
- website/content/en/docs/Getting Started/latest/security.md
Fixes broken links in Operator 0.6 docs
> Docs: Fix broken links

- website/content/en/docs/Getting Started/latest/installing-the-operator.md
* Added minor changes to the installation guide.
review them:
```
- API changes
- Bug fixes
```
> Updated docs

- website/content/en/docs/Getting Started/latest/customizing-jenkins.md
Follow-up of https://github.com/jenkinsci/kubernetes-operator/pull/670
Update of the docs following this PR: https://github.com/jenkinsci/kubernetes-operator/pull/670
review them:
```
- …
```
> fix(doc): update jenkins plugins versions in doc

- chart/jenkins-operator/.helmignore
Fixes #689
Update `.helmignore`  to not included packaged charts in helm state.
review them:
- Bug fixes
- Do not included extra files in helm state
> #689 ignore packaged helm charts

- api/v1alpha2/jenkins_types.go
- chart/jenkins-operator/crds/jenkins-crd.yaml
- chart/jenkins-operator/values.yaml
- config/crd/bases/jenkins.io_jenkins.yaml
- go.mod
- pkg/configuration/user/seedjobs/seedjobs.go
- pkg/configuration/user/seedjobs/validate.go
- pkg/configuration/user/seedjobs/validate_test.go
- pkg/plugins/base_plugins.go
- test/e2e/configuration_test.go
https://github.com/jenkinsci/kubernetes-operator/issues/695
> Remove cron validation

- chart/jenkins-operator/templates/jenkins.yaml
- chart/jenkins-operator/values.yaml
Signed-off-by: tombokombo <tombo@sysart.tech>
Add posibility to override hosts (/etc/hosts) on pod level.
review them:
> helm chart: hostAliases support

- chart/jenkins-operator/templates/jenkins.yaml
- chart/jenkins-operator/values.yaml
add 'nodeSelector' item into jenkins-operator helmchart.
review them:
> Customize jenkins-operator helmchart with adding 'nodeSelector'

- .github/workflows/release.yaml
- Makefile
- api/v1alpha2/zz_generated.deepcopy.go
* added a workflow that releases Operator (project, as well as image)
* re-generated deepcopy
> chore: add release workflow

- chart/jenkins-operator/values.yaml
- pkg/configuration/backuprestore/backuprestore.go
- pkg/configuration/base/resources/route.go
- pkg/configuration/base/resources/service.go
- pkg/plugins/base_plugins.go
- test/e2e/configuration_test.go
- test/e2e/jenkins_pod_restart_test.go
- test/e2e/mode_kubernetes.go
- test/e2e/restart_test.go
- test/e2e/test_utility.go
- test/e2e/wait.go
- test/helm/helm_test.go
Add the new jenkins lts version: 2.375.3 
review them:
> chore(update): use latest jenkins lts: 2.375.3

- .github/workflows/release-backup.yaml
- .github/workflows/release.yaml
- README.md
- chart/jenkins-operator/README.md
- chart/jenkins-operator/values.yaml
- website/content/en/_index.html
Added the new gitter/matrix channel
review them:
```
- Doc updates
```
> chore(doc): Add the new chat references

- README.md
Update the security links in the README as these currently navigate to 404
review them:
```
- README Updates
```
> chore(doc): Update links in README

- .github/workflows/auto-stale-issue.yaml
> feat(repo): add stale bot

- pkg/configuration/user/reconcile.go
Fix #843 ?
review them:
```
- API changes
- Bug fixes
```
> feat: attempt to move restore before seed job creation

- .github/workflows/auto-gen-docs.yaml
- .github/workflows/release-backup.yaml
- backup/pvc/Makefile
review them:
```
- API changes
- Bug fixes
```
> fix: hugo and backup ci again

- README.md
- chart/jenkins-operator/README.md
- chart/jenkins-operator/values.yaml
Small preparation for v0.8.0-beta2 code cut
review them:
```
- API changes
- Bug fixes
```
> chore: preparing v0.8.0-beta2 version bump

- .github/dependabot.yml
- .github/workflows/auto-generate-manifests.yaml
review them:
```
- API changes
- Bug fixes
```
> chore(ci): remove some garbage from auto-generate manifests

- .github/dependabot.yml
- .github/workflows/auto-generate-manifests.yaml
review them:
```
- API changes
- Bug fixes
```
> fix(ci): auto generate manifests cleanup

- .devcontainer/devcontainer.json
- .github/dependabot.yml
- .github/workflows/auto-tests-bats.yaml
- Makefile
- test/bats/test_helper.bash
review them:
```
- API changes
- Bug fixes
```
> fix(ci): update devcontainer, github actions config

- Makefile
review them:
```
- API changes
- Bug fixes
```
> fix: mkdir bin before link helm

- .github/workflows/auto-gen-docs.yaml
- nix/website-build.nix
- website/content/en/community/_index.md
review them:
```
- API changes
- Bug fixes
```
> fix(website): base url in website build

- api/v1alpha2/jenkins_types.go
Fix the broken links on the Jenkins API type docs
review them:
> Fix broken links on Jenkins API type docs

- test/bats/2-deploy-with-more-options.bats
- test/bats/test_helper.bash
Fixes recent CI failure during bats-tests due to addition of checks for updating of the preStop lifecycle hook of the jenkins master container.
review them:
- [ x ] Includes tests (if functionality changed/added)
- [ x ] Includes docs (if user facing)
- [ x ] Commit messages follow [commit message best practices](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md#commit-messages)
> fix(bats-tests): lifecycle hook injection test failing

- .github/workflows/auto-gen-docs.yaml
- .github/workflows/auto-generate-manifests.yaml
- .github/workflows/auto-stale-issue.yaml
- .github/workflows/auto-tests-bats.yaml
- .github/workflows/auto-tests-e2e.yaml
- .github/workflows/auto-tests-helm.yaml
- .github/workflows/release-backup.yaml
- .github/workflows/release-helm-chart.yaml
- .github/workflows/release-nightly.yaml
- .github/workflows/release.yaml
- .pre-commit-config.yaml
- flake.lock
- flake.nix
- go.mod
- nix/gomod2nix.toml
- pin github actions to a tag ref
- update and freeze pre-commit hooks
- add pin-github-actions hooks
- bump nix flake stable/rolling and gomod2nix
- format nix flakes
> chore: pin github actions, update and freeze pre-commit hooks, update nix flake

- .github/workflows/auto-tests-bats.yaml
- Makefile
- kind-cluster.yaml
- test/bats/1-deploy.bats
- test/e2e/jenkins_test.go
- test/e2e/test_utility.go
> feat: add matrix tests for bats and replace the old devoptics plugin in tests

- website/content/en/docs/Getting Started/latest/custom-backup-and-restore.md
> docs: improve
