- Makefile
Hi team,
this is a small PR to make `make build`more silent in case of generated docs directory does not exist.
Currently it displays an error which is a bit confusing.
> Make make more silent in case of generated docs directory does not exist

- deploy/crds/jenkins_v1alpha2_jenkins_cr.yaml
- openshit-jenkins.yaml
- pkg/apis/jenkins/v1alpha2/jenkins_types.go
- pkg/controller/jenkins/configuration/base/reconcile.go
- pkg/controller/jenkins/configuration/base/resources/pod.go
Hi team,
this PR is intended to improve reusability of the Jenkins operator. With the current code, the image UID is hardcoded in the controller and has to SecurityContext.runAsUser to be run. This causes some issues in environments with more strict SecurityContextConstraints.
Also, the example Jenkins CR has been provided to show how one can override the default "Command" which is also kind of hardcoded in the controller.
> Externalize hardcoded image uid and pod Security Context and removes default Command

- docs/security.md
I think the fix for this would be something along the lines of:
* Make the operator tolerate not being able to create RBAC resources for master nodes
* Document a more secure mode of deploying the operator, which does not grant permissions on `rbac.authorization.k8s.io/*` or `ServiceAccounts`, and requires the Jenkins Master role to be deployed in parallel with any `Jenkins` resources.
In this scenario, having `pod/exec` would not be an escape hatch and cluster administrators could more easily reason about restrictions on namespaces intended to house Jenkins instances, and retain control over sensitive things like ResourceQuotas and Secrets in those namespaces without having to create complex admission controllers to patch over this vulnerability.
> Document known RBAC privilege escalation vulnerability

- backup/pvc/bin/run.sh
- backup/pvc/e2e/limit_backup_count/test.sh
In our testing we ran into an issue testing the backup utility. The `backup` container was crashing due to the failing `rm` command as it encountered a `lost+found` directory in our `pvc`.
This PR adds a `grep` command to filter out only valid backup files so only these are scheduled for removal allowing the container to finish gracefully.
> Filter for valid backups before trying to remove them

- backup/pvc/bin/run.sh
If there is no backup file then `grep` exit with nonzero code.
So use `find` instead of it.
> Support no backup file case.

- pkg/controller/jenkins/plugins/plugin.go
- pkg/controller/jenkins/plugins/plugin_test.go
Upper/Camel case is a valid plugin name in jenkins, this change is adding the insensitive flag to the plugin name validation in order to accept such plugins.
fix #109
> change plugin name regex to case-insensitive.

- pkg/controller/jenkins/configuration/base/validate_test.go
- pkg/controller/jenkins/plugins/plugin.go
This change is it allow all possible versions in all plugins within update.jenkins.io, this is linked to issue:https://github.com/jenkinsci/kubernetes-operator/issues/144
> Updating plugin.go to allow versions

- pkg/apis/jenkins/v1alpha2/jenkins_types.go
- pkg/controller/jenkins/configuration/base/resources/base_configuration_configmap.go
Jenkins Plugin implementations which use PluginServletFilter instead of HudsonFilter invalidate POST requests which are valid. To allow users to be able to use those plugins, this would be a helpful toggle.
- CSRF Protection is enabled by default.
- Adding `enableCSRFProtection: false` under `jenkins.spec.master` will disable CSRF protection for the Jenkins instance.
> Add ability to disable CSRFProtection in the Jenkins master

- pkg/controller/jenkins/client/jenkins.go
This bug makes it impossible to use NodePort instead of port.
> Quick fix ports in jenkins.go

- test/e2e/configuration_test.go
- test/e2e/operator.go
- test/e2e/restart_test.go
- test/e2e/restorebackup_test.go
- test/e2e/seedjobs_test.go
- test/e2e/wait.go
Due to the lack of the E2E tests information about what's gone wrong when a test fails, we decided to improve the logging mechanism:
* After a test fails, the pods in the namespace will be listed and printed
* After a test fails, the Kubernetes events in the namespace will be listed and printed
* After a test fails, the operator logs will be printed
> Add E2E tests logging mechanism

- Makefile
- pkg/controller/jenkins/jenkins_controller.go
This quick bugfix resolves these issues:
* When `make minikube-run` command is executed, the operator informs that `--namespace` argument does not exist
* When `--jenkins-api-use-nodePort` flag is `true` operator creates a `NodePort` type service instead of `ClusterIP` so this flag will work properly
> Fix startup issues

- website/content/en/docs/Security/_index.md
On the Security page, just below the subheader `Kubernetes` there is a list being displayed inline with the text. No markdown expert here, but assuming the newline will fix the rendering here as it was done in the previous subheader `Jenkins Hardening`.
> Render markdown list properly

- go.mod
- go.sum
- pkg/apis/jenkins/v1alpha2/jenkins_types.go
- pkg/controller/jenkins/configuration/user/seedjobs/seedjobs.go
- pkg/controller/jenkins/configuration/user/seedjobs/validate.go
- pkg/controller/jenkins/configuration/user/seedjobs/validate_test.go
This PR adds the ability to enable a Bitbucket push trigger for the seed job. It follows the same patterns that were established for the GitHub trigger.
I am not sure what the versioning criteria is, so I left it as 0.3.3 for now.
> Add Bitbucket trigger for seed job

- website/content/en/docs/Security/_index.md
Have Updated Few Broken Links that was not working with the https://jenkinsci.github.io/kubernetes-operator/docs/security/ . If its still not working as expected. I would be happy to write for the documentation.
> Broken Link Fixes

- website/content/en/docs/Getting Started/latest/configuration.md
Url without protocol was causing failure of Seed Job. So updated the corresponding URL
> SSH URL Update in The Repository Url

- docs/docs/getting-started/latest/notifications/index.html
- website/content/en/docs/Getting Started/latest/notifications.md
Fix documentation regarding notifications.
In the documentation examples field is called `loggingLevel`, which is not aligned with [schema](https://github.com/jenkinsci/kubernetes-operator/blob/master/pkg/apis/jenkins/v1alpha2/jenkins_types.go#L108) where the field is called `level`. Fix inconsistency by updating the documentation.
review them: …
> Fix documentation regarding notifications

- deploy/crds/openshift_jenkins_v1alpha2_jenkins_cr.yaml
- deploy/role.yaml
- pkg/controller/jenkins/configuration/base/resources/rbac.go
Changes the default RulePolicies for the jenkins-operator-${jenkins.spec.name} role.
review them:
```
Role jenkins-operator-jenkins now has default permissions required by OpenShift
```
> Default rule policy now allows watching resources required by OpenShift

- config.openshift.env
- deploy/crds/openshift_jenkins_v1alpha2_jenkins_cr.yaml
- pkg/controller/jenkins/configuration/base/reconcile_test.go
- pkg/controller/jenkins/configuration/base/resources/rbac.go
- pkg/controller/jenkins/configuration/base/serviceaccount.go
- website/content/en/docs/Getting Started/latest/openshift.md
Updates latest documentation to add an OpenShift section.
Some debug logs have been added also to serviceaccount.go to understand the usage of serviceAccount attribute of the CRD.
review them:
none
```
Add OpenShift section in the latest documentation
```
> Adding OpenShift doc

- cmd/manager/main.go
- pkg/apis/apis.go
- pkg/controller/jenkins/configuration/base/reconcile.go
- pkg/controller/jenkins/configuration/base/resources/route.go
- pkg/controller/jenkins/configuration/base/resources/service.go
- pkg/controller/jenkins/configuration/base/route.go
- pkg/controller/jenkins/handler.go
- pkg/controller/jenkins/jenkins_controller.go
Add Route pointing to the HTTP Service when the Route API is present
review them:
```
If the Route API is available, its Scheme is registered and the route reconciliation is enabled.
```
> Add Route pointing to the HTTP Service when the Route API is present

- cicd/pipelines/build.jenkins
- docs/docs/getting-started/latest/configuration/index.html
- docs/docs/getting-started/latest/index.xml
- docs/docs/getting-started/v0.1.x/configuration/index.html
- docs/docs/getting-started/v0.1.x/index.xml
- docs/docs/getting-started/v0.2.x/configuration/index.html
- docs/docs/getting-started/v0.2.x/index.xml
- docs/docs/getting-started/v0.3.x/configuration/index.html
- docs/docs/getting-started/v0.3.x/index.xml
- docs/docs/index.xml
- pkg/controller/jenkins/configuration/user/seedjobs/seedjobs.go
- website/content/en/docs/Getting Started/latest/configuration.md
- website/content/en/docs/Getting Started/v0.1.x/configuration.md
- website/content/en/docs/Getting Started/v0.2.x/configuration.md
- website/content/en/docs/Getting Started/v0.3.x/configuration.md
`jenkins/jnlp-slave:alpine` used as the iamge for seedjobs agents is now deprecated as gven in https://hub.docker.com/r/jenkins/inbound-agent/ and is replaced here with `jenkins/inbound-agent:alpine`
review them:
``` …
```
> Update deprecated agent to supported image used in SeedJobs Agents

- Makefile
when the tests run into a docker container, the makefile tries to get the jenkins command from the docker container using minikube ip command which is complaining.
Instead, if minikube is not found, it will use 127.0.0.1 ip address.
> Makefile complains about minikube not found when running inside docker

- pkg/controller/jenkins/configuration/base/reconcile.go
- pkg/controller/jenkins/configuration/base/reconcile_test.go
- pkg/controller/jenkins/configuration/base/validate_test.go
- pkg/controller/jenkins/configuration/user/reconcile.go
- pkg/controller/jenkins/jenkins_controller.go
- test/e2e/jenkins.go
I propose avoid passing logger as argument in function signature because it is confusing, adding complexity.
we can either add and init the logger in the struct object in order to use it on underlying method or just add it in method 
for example:
return &ReconcileJenkinsBaseConfiguration{
Configuration:                config,
logger:                       log.Log.WithValues("cr", config.Jenkins.Name),
jenkinsAPIConnectionSettings: jenkinsAPIConnectionSettings,
}
or here:
func (r *ReconcileJenkins) Reconcile(request reconcile.Request) (reconcile.Result, error) {
reconcileFailLimit := uint64(10)
logger := logx.WithValues("cr", request.Name)
review them:
_See [the contribution …
> refactor log handling

- pkg/apis/apis.go
- pkg/controller/jenkins/configuration/backuprestore/backuprestore.go
- pkg/controller/jenkins/configuration/base/deployment.go
- pkg/controller/jenkins/configuration/base/reconcile.go
- pkg/controller/jenkins/configuration/base/resources/deployment.go
- pkg/controller/jenkins/configuration/base/resources/pod.go
- pkg/controller/jenkins/configuration/base/validate_test.go
- pkg/controller/jenkins/configuration/configuration.go
- test/e2e/jenkins.go
Part of refactor for https://github.com/jenkinsci/kubernetes-operator/issues/195
Allows for using the annotation `jenkins.io/use-deployment`
and setting the value to `true` makes the operator use a
Deployment instead of Pod for serving Jenkins.
- Refactor from `base/resources/pod.go` to `base/resources/deployment.go`
- Added conditional creation and reconciliation for Deployement resource if `jenkins.io/use-deployment` annotation is set to `true`
IMPORTANT NOTE:
The dependency on annotation is only temporary and the logic from reconciling with the Pod will be moved completely in the upcoming PRs for refactoring.
review them:
_See [the contribution guide](https://github.com/jenkinsci/kubernetes-operator/blob/mast …
> Use Deployment instead of Pod (intermediate PR)

- chart/jenkins-operator/Chart.yaml
The chart is already in the format of a Helm 3 chart, however the `apiVersion` of the chart is set to `v1`, which is used for Helm 2 charts. Helm 3 charts should use `apiVersion: v2`.
This makes tools such as ArgoCD mistake the chart for a Helm 2 chart, and therefore template the chart using the wrong helm version. In ArgoCDs case, that means that the CRDs aren't deployed.
reference: https://helm.sh/docs/faq/#chartyaml-apiversion-bump
review them:
If API changes are included, additive changes must be approved by at least two [OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/ …
> Change helm chart to helm 3 apiVersion

- pkg/configuration/user/casc/casc.go
Casc version 1.41 introduced changed to [YamlSource](https://github.com/jenkinsci/configuration-as-code-plugin/blob/configuration-as-code-1.41/plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlSource.java) which breaks the current implementation in the operator. The commit checks the version of casc and loads the yaml accordingly.
Check casc plugin version, to accommodate for api changes in version casc v1.41 in  [YamlSource](https://github.com/jenkinsci/configuration-as-code-plugin/blob/configuration-as-code-1.41/plugin/src/main/java/io/jenkins/plugins/casc/yaml/YamlSource.java)
review them:
_See [the contribution guide](https://github.com/jenkinsci/kubernetes-operator/blob/master/CONTRIBUTING.md) for more …
> Check casc version to match changes in YamlSource

- chart/jenkins-operator/templates/jenkins.yaml
- chart/jenkins-operator/values.yaml
- website/content/en/docs/Installation/_index.md
Added configuration option for the user to specify annotations and labels for Jenkins CR and pod via helm. Updated installation guide with information about this feature.
#432
> Added labels and annotations to Helm Chart

- pkg/configuration/base/reconcile.go
- pkg/configuration/base/resources/service.go
- pkg/configuration/base/service.go
- test/e2e/configuration_test.go
- test/e2e/jenkins.go
Made the targetPort in Jenkins pod a fixed value.
Previously users encountered issue with changing values.
Added test comparing expected and actual targetPort values.
#439
> Fixed targetPort value

- .github/workflows/auto-tests.yaml
Switched from running tests on Travis to GitHub Actions.
> Tests running on GitHub Actions

- chart/jenkins-operator/templates/jenkins.yaml
Small addition the the Helm Jenkins instance file. `getLatestAction` variable is not passed event though it is defined in `values.yaml`.
review them:
> Pass getLatestAction Helm value to the Jenkins instance

- go.mod
- pkg/configuration/user/seedjobs/validate.go
- pkg/configuration/user/seedjobs/validate_test.go
Reported in #539.
Changed the way the operator is performing ssh private key validation. It will now use `ssh.ParseRawPrivateKey` to validate the key. This allows the user to use keys **other** than PEM encoded RSA. 
ed25519 is often recommended to be used if it's supported. Using this algorithm implies the use of OpenSSH key format in ssh-keygen.
> #539 Allow More SSH Private Key Formats

- pkg/configuration/base/reconciler.go
Hotfix for the incompatibility between the Operator and Kubernetes 1.21.
Kubernetes in 1.21 ships with `BoundServiceAccountTokenVolume` enabled, which causes the service account admission controller to add a new volume: `kube-api-access-<random-suffix>`. That is causing the operator to loop over comparing the actual and expected volumes. Now that new volume will not be compared.
Kubernetes reference: https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume
> Skip kube-api-access Volume Comparison

- pkg/configuration/user/seedjobs/validate.go
- website/content/en/docs/Getting Started/Preview/configuration.md
- website/content/en/docs/Getting Started/latest/configuration.md
Reported in: https://github.com/jenkinsci/kubernetes-operator/issues/552
Fixes a problem where the operator tries to look for `external` credential type in Kubernetes secrets and fails.
The operator shouldn't try to fetch credentials that have their types defined as `external` - that means that credentials are supplied externally, without using k8s secrets (using e.g. Configuration As Code or Groovy Script).
Docs: https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/configuration/#external-authentication
> #552 Seed Jobs: Don't Validate "external" Credential Type

- pkg/plugins/base_plugins.go
Update Kubernetes Plugin to 1.30.0. The sub-plugin `kubernetes-client-api` has released it's major version 5.4.1 which is not compatible with `kubernetes:1.29.6`, but unfortunately the startup script of the jenkins will install `kubernetes-client-api:5.4.1` which ends up in all kind of strange issues. Like for us it started to endlessly create pods because of this error:
`java.lang.NoSuchMethodError: io.fabric8.kubernetes.client.dsl.PodResource.watch`
I tested this with adding 
```
basePlugins:
- name: kubernetes
version: 1.30.0
- name: workflow-job
version: '2.41'
- name: workflow-aggregator
version: '2.6'
- name: git
version: 4.7.2
- name: job-dsl
version: '1.77'
- name: configuration-as-code
version: '1.51'
- name: kubernetes-credentials-provider
version: 0.18-1
``` 
to the helmfiles …
> update kubernetes to 1.30.0

- website/content/en/docs/Getting Started/latest/configure-backup-and-restore.md
Related to: 
- https://github.com/jenkinsci/kubernetes-operator/issues/596
- https://github.com/jenkinsci/kubernetes-operator/issues/481
Added an explanation why the backup script saves only job history.
> Docs: explanation what is backed up and why

- pkg/configuration/user/seedjobs/seedjobs.go
Should fix seedjob agent's problems with DNS reported in https://github.com/jenkinsci/kubernetes-operator/issues/528
> Bump seedjobs agent image version to 4.9-1

- pkg/configuration/user/seedjobs/seedjobs.go
We now add GitLFS pull after checkout behaviour in order to support also repositories which are relying on Git LFS.
Closes #482
Seed jobs can not clone repositories which contain lfs files.
review them:
N/A
N/A
> Seed jobs can not clone repositories which contain lfs files.

- chart/jenkins-operator/values.yaml
- website/content/en/docs/Getting Started/latest/schema.md
- website/content/en/docs/Installation/_index.md
* add information on other restricted volumeMounts besides jenkins-home to docs
* link there from schema
* link there from Helm chart default values.yaml
> Docs: add info on other restricted volumeMounts

- chart/jenkins-operator/Chart.yaml
- chart/jenkins-operator/templates/_role.yaml
- chart/jenkins-operator/templates/role_binding.yaml
- chart/jenkins-operator/values.yaml
If jenkins.namespace is set to "", it leads to WATCH_NAMESPACE
environment value of Jenkins Operator itself to be set to "", which
leads that operator watches all namespaces (see
#77 (comment)).
This case requires custom handling: instead of creating role and
role_binding we need to create clusterrole and clusterrolebinding with
the required permissions.
review them:
If API changes are included, additive changes must be approved by at least two [OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS) and backwards incompatible changes must be approved by [more than …
> Add handling of empty WATCH_NAMESPACE value of jenkins.namespace 

- chart/jenkins-operator/templates/role.yaml
- chart/jenkins-operator/templates/role_binding.yaml
Modified Jenkins Operator Role and RoleBinding templates to create Role and RoleBinding in neither Jenkins nor Operator namespace if Jenkins namespace is an empty string (because in this case, ClusterRole and ClusterRoleBinding are created).
> Helm chart: fix creating role and rb when jenkins namespace is empty

- .github/workflows/auto-gen-docs.yaml
Adds a step to workflow for autogenerating docs that updates 'last modified' date in the markdowns that were modified in a commit that triggered the workflow.
> Add step to update 'last modified' date in docs autogen workflow

- Makefile
- chart/index.yaml
* Fixes users not being able to install latest version of Operator via Helm chart (https://community.jenkins.io/t/failed-to-install-jenkins-operator-using-helm/306/2)
* Fixes Makefile goal for releasing Helm chart to avoid this issue coming up in the future
> Fix Helm package URL in Makefile & Index entry for 0.5.3

- .github/workflows/auto-gen-docs.yaml
Excluded deleted files from arguments to date update script in doc gen workflow by using --diff-filter option for grep
> Fix docs autogen workflow case where files were deleted

- api/v1alpha2/jenkins_types.go
- pkg/configuration/base/resources/deployment.go
- pkg/configuration/base/resources/pod.go
- pkg/configuration/user/seedjobs/seedjobs.go
Add HostAliases to schema and propagate them to pods so the user can add entries to /etc/hosts
> Add HostAliases to schema

- chart/jenkins-operator/values.yaml
Update seed-job-creation-tutorial link referenced in values.yaml
- Update the documentation link to a non 404 page
- Remove secondary link for additional information (It appears the 2nd link was entirely removed during the documentation refactor that broke this?)
review them:
``` …
```
> Update broken documentation links

- .github/workflows/release-helm-chart.yaml
Workflow was failing because it didn't account for "version:" pattern appearing more than once in the Chart.yaml file.
* modified sed usage to account for dependencies section now present in Chart.yaml
* now sed only looks for the first line with "version:"
> Chore: fix Helm chart release workflow breaking

- chart/jenkins-operator/templates/jenkins.yaml
Do not strip leading whitespace from `priorityClassName` in helm template
fixes #685
review them:
- Bug fixes
Allow specifying jenkins `priorityClassName` within helm chart
> #685 Do not strip leading whitespace from priorityClassName in helm template

- chart/jenkins-operator/templates/jenkins.yaml
- chart/jenkins-operator/values.yaml
This is necessary in order to be able to provide the annotations attached to the
service account associated with the Jenkins master instance.
I have made the small changes necessary in order to enable adapting the `ServiceAccount` used by the master Jenkins which is provisioned with the default Helm chart.
review them: …
> Fixes #687 - Enable customization of master Jenkins service account via default Helm template

- pkg/plugins/plugin.go
- pkg/plugins/plugin_test.go
New jenkins plugin versions have underscores in them (example: https://plugins.jenkins.io/credentials/). The operator refuses configuration for such plug-ins as they do not match the existing regex.
review them:
``` …
```
> Receive plugins' versions with underscores.

- Dockerfile
- Makefile
- api/v1alpha2/jenkins_types.go
- chart/jenkins-operator/crds/jenkins-crd.yaml
- chart/jenkins-operator/values.yaml
- config/crd/bases/jenkins.io_jenkins.yaml
- pkg/constants/constants.go
- pkg/plugins/base_plugins.go
- test/e2e/configuration_test.go
- test/e2e/jenkins_test.go
- test/e2e/restorebackup_test.go
- test/e2e/test_utility.go
- test/helm/helm_test.go
Changed Dockerfile & Makefile to build a multi-platform (amd64 and arm64) image of jenkins-operator.
Using `TARGETOS` and `TARGETARCH` in the builder and leverage `docker build build` command in the Makefile.
:boom: Breaking changes :boom:
It is required to run `docker buildx create --use` before being able to create & push the image to registry.
Currently podman does not support buildx features, this changes requires `CONTAINER_RUNTIME_COMMAND=docker`.
🧪 Unit tests changes 🧪 
Fixing unit tests with the following changes:
* reduce Jenkins CPU requirements from `1` to `250m`
* upgrade Jenkins image to `jenkins/jenkins:2.319.3-lts`
```
Support multi-arch (amd64 and arm64) container image.
Upgrade base plugins to following versions:
* configuration-as-code: v1346.ve8cfa_3473c94
* git: 4.10.3 …
```
> Build multi-arch images

- .github/workflows/deploy-nightly.yaml
- Makefile
Before building with buildx driver need to be specified through docker buildx create
I tested it on my fork and it seems ok, failing only because i didnt have the credentials to push:
https://github.com/bhubert/kubernetes-operator/runs/5214195607?check_suite_focus=true
review them:
> Fix release pipeline

- api/v1alpha2/jenkins_types.go
- chart/jenkins-operator/crds/jenkins-crd.yaml
- chart/jenkins-operator/values.yaml
- pkg/configuration/user/seedjobs/seedjobs.go
- pkg/configuration/user/seedjobs/seedjobs_test.go
In my company we need to deploy a kubernetes cluster on ARM64 computers.
The image used by the seed agent is hardcoded with an AMD64 image which is a blocker for us.
This PR will allow users to specify the image they want for the seed agent.
If not specified the image previously hardcoded will be used.
Without this commit, previous PR about multi-arch is not really usefull since the seed agent wont follow the operator architecture.
resolves https://github.com/jenkinsci/kubernetes-operator/issues/700
review them:
```
API changes:
A new seedJobAgentImage can be used to specify the image …
```
> Allow to specify seed agent image

- .golangci.yml
- config/crd/bases/jenkins.io_jenkins.yaml
When i added the option to specify the seed job agent image (in this commit : https://github.com/jenkinsci/kubernetes-operator/commit/56b65aed167fd4742c24cad49347006232343cdf) i just noticed that i forgot to update the CRD mentioned in the documentation : https://jenkinsci.github.io/kubernetes-operator/docs/getting-started/latest/installing-the-operator/
Sorry for the two part commit
review them:
If API changes are included, additive changes must be approved by at least two [OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS) and backwards incompatible changes …
> Add seedJobAgentImage into CRD

- website/content/en/docs/Getting Started/latest/schema.md
Link from Schema docs to seed job is broken
review them:
~~- [ ] Includes tests (if functionality changed/added)~~ N/A
```
- Fix broken link on Operator Schema doc
```
> Fix broken link for configuring seed jobs

- chart/jenkins-operator/templates/jenkins.yaml
The allowance to specify a seedjob agent image was introduced in #718 and #754.
While I specify the agent image in my values.yaml, the default agent image is still used.
This PR adds the seedjob agent image to the Jenkins chart.
review them:
> adding seedjobagentimage to jenkins chart

- deploy/all-in-one-v1alpha2.yaml
Increase the memory limits for the kubernetes operator
I found that with the previous limits, it would repeatedly be OOM-killed,
before I had even added any jenkins.
Fixes #773
> Increase the memory limits for the kubernetes operator

- chart/jenkins-operator/values.yaml
- docs/docs/getting-started/latest/index.xml
- docs/docs/getting-started/latest/installing-the-operator/index.html
- docs/docs/index.xml
- test/e2e/restorebackup_test.go
- website/content/en/docs/Getting Started/latest/configuring-backup-and-restore.md
- website/content/en/docs/Getting Started/latest/installing-the-operator.md
For the current operator version, update the scripts and documentation for image `virtuslab/jenkins-operator-backup-pvc` to tag `v0.1.1`. This is the most recent tag: https://hub.docker.com/r/virtuslab/jenkins-operator-backup-pvc/tags
Documentation for old versions of the operator is not updated.
I have not tested any of this.
review them: …
> update image tag for `virtuslab/jenkins-operator-backup-pvc`

- chart/jenkins-operator/values.yaml
When this https://github.com/jenkinsci/kubernetes-operator/pull/784 was merged I forgot to remove the temporary operator img and put the official virtuslab one, this PR is revering that change by adding the latest operator img built 6 days ago.
When a new version will be officially tagged obv this will be superseeed by new official "operator tagged version".
review them:
> chore(operator): update operator version in master

- chart/jenkins-operator/templates/jenkins.yaml
- chart/jenkins-operator/values.yaml
Add possibility to set tolerations for jenkins pod. 
review them:
```
- Add tolerations for jenkins pod in helm chart
```
> Add tolerations for jenkis pod

- variables.mk
Missing arg causing fatal error when running make cmds
Update git ls-files cmd with missing arg. This is currently causing a fatal error when running make cmds
review them:
> chore: Update git ls-files cmd with missing arg

- backup/pvc/Dockerfile
- backup/pvc/bin/backup.sh
- backup/pvc/bin/get-latest.sh
- backup/pvc/bin/restore.sh
- backup/pvc/bin/run.sh
- backup/pvc/e2e/backup_and_restore/test.sh
- backup/pvc/e2e/get-latest/test.sh
- backup/pvc/e2e/limit_backup_count/test.sh
- backup/pvc/e2e/tmp_dir_clean_after_backup_creation/test.sh
* Fix backup script: in case of warnings (like files changes while reading) do not fail the backup
* Use zstd by default should be faster than gz especially in situations where you have a lot of jobs
review them:
```
* Fix backup script: in case of warnings (like files changes …
```
> feat: use zstd instead of gz by default, fix the backup script

- .github/workflows/auto-codespell.yml
- backup/pvc/bin/get-latest.sh
`get-latest.sh` should support both gz and zstd to let the users migrate easily to zstd standard
review them:
```
- API changes
- Bug fixes
```
> fix(backup): get-latest.sh, search for both .gz and .zstd

- chart/jenkins-operator/values.yaml
- pkg/plugins/base_plugins.go
- test/bats/2-deploy-with-more-options.bats
- test/e2e/configuration_test.go
- test/helm/helm_test.go
review them:
```
- API changes
- Bug fixes
```
> fix(tests)

- chart/jenkins-operator/templates/jenkins.yaml
Update backup container `imagePullPolicy` to align with jenkins-master
Fix https://github.com/jenkinsci/kubernetes-operator/issues/914
`helm-test` pass log:
```
=== RUN   TestHelm
Running Suite: Controller Suite
===============================
Random Seed: 1701152304
Will run 3 of 3 specs
STEP: bootstrapping test environment
{"level":"info","ts":1701152304.5420983,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
Jenkins Controller with security validator When Jenkins CR contains plugins with security warnings 
Denies creating a jenkins CR with a warning
/workspaces/jenkins-operator/test/helm/helm_test.go:102
STEP: creating temporary namespace
{"level":"info","ts":1701152304.542624,"logger":"controller-runtime.manager","msg":"starting …
```
> Fix: use consistent imagePullPolicy when enable Jenkins backup

- chart/jenkins-operator/values.yaml
Change default value for configurationAsCode and groovyScripts to remove warning on Helm chart installation.
```
coalesce.go:286: warning: cannot overwrite table with non table for jenkins-operator.jenkins.configuration.configurationAsCode (map[])
coalesce.go:286: warning: cannot overwrite table with non table for jenkins-operator.jenkins.configuration.groovyScripts (map[])
```
review them:
If API changes are included, additive changes must be approved by at least two [OWNERS](https://github.com/jenkinsci/kubernetes-operator/blob/master/OWNERS) and backwards incompatible changes must be …
> Fix: change default value for configurationAsCode and groovyScripts

- website/content/en/docs/Getting Started/v0.7.x/ldap.md
Modified ldap.md file where the yaml code was not displaying as it was supposed to be displayed. 
Fixing issue #937
> Modified ldap.md for issue #937

- chart/jenkins-operator/templates/operator.yaml
- chart/jenkins-operator/values.yaml
- website/content/en/docs/Getting Started/latest/installing-the-operator.md
In case the Jenkins instance is disabled, this commit allows us to pick a different namespace for the deployment by configuring the operator object instead of the jenkins object.
Adds a new operator.watchNamespace value that should be used in case jenkins.enabled is set to false. 
Updates and cleans up the documentation to reflect this change.
review them: …
> Provides an Override to the WATCH_NAMESPACE env variable.

- .github/workflows/auto-tests-bats.yaml
- .github/workflows/auto-tests-e2e.yaml
- .github/workflows/auto-tests-helm.yaml
- .pre-commit-config.yaml
- flake.nix
- test/e2e/jenkins_configuration_test.go
- test/e2e/jenkins_pod_restart_test.go
- test/e2e/jenkins_test.go
- test/e2e/restorebackup_test.go
- test/e2e/test_utility.go
- test/helm/helm_test.go
- test/make_matrix_ginkgo.sh
- make ginkgo tests as matrix for easily re-run failing tests or checking logs
- fix pod restart check
review them:
```
```
> feat: make ginkgo tests as matrix

- backup/pvc/bin/backup.sh
- website/content/en/docs/Getting Started/latest/configuring-backup-and-restore.md
use atomic mv to create backup to avoid broken unrestorable backups
```
% k exec jenkins-jenkins -c backup -- df -hT | grep -E "overlay|ext4"
overlay        overlay  110G   23G   88G  21% /
/dev/nvme2n1   ext4      64G   23G   42G  36% /backup
```
https://github.com/jenkinsci/kubernetes-operator/blob/cf49a4a28fbb1af5250031ce89b0a5267d81aca1/backup/pvc/bin/backup.sh#L8C1-L8C15
```
BACKUP_TMP_DIR=$(mktemp -d)
```
https://www.gnu.org/software/autogen/mktemp.html
```
--tmpdir[=DIR]  interpret TEMPLATE relative to DIR.  If DIR is not
specified, use $TMPDIR if set, else /tmp.  With
this option, TEMPLATE must not be an absolute name.
Unlike with -t, TEMPLATE may contain slashes, but
mktemp creates only the final component
```
https://www.gnu.org/software/coreutils/manual/html_node/mv-invocation.h …
> fix(backup): use atomic mv to create backup

- pkg/client/jenkins.go
Looking on the upstream [code](https://github.com/jenkinsci/jenkins/blob/2336ac5ffac2a06d4377a7c7623d95311dc8ea46/core/src/main/java/hudson/slaves/SlaveComputer.java#L861-L888) we need to change this method [here](https://github.com/jenkinsci/kubernetes-operator/blob/0911dfe64a122d8727a383da40dfd9ed2c082a6b/pkg/client/jenkins.go#L201) to avoid a verbose deprecation message in jenkins logs.
fix #1024 
review them:
```
> fix(operator): deprecated jnlpUrl
